version: "3.9"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: glific_dev
    ports:
      - "5432:5432"
    networks:
      - glific_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: glific_dev
      DB_HOST: postgres
    ports:
      - "4000:4000"
    networks:
      - glific_network

networks:
  glific_network:
